# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_now_v2_integration import ServiceNowV2Integration  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceNowV2Integration(unittest.TestCase):
    """ServiceNowV2Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceNowV2Integration(self):
        """Test ServiceNowV2Integration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_now_v2_integration.ServiceNowV2Integration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
