# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_forwarding_rules_response import ListForwardingRulesResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListForwardingRulesResponse(unittest.TestCase):
    """ListForwardingRulesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListForwardingRulesResponse(self):
        """Test ListForwardingRulesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_forwarding_rules_response.ListForwardingRulesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
