# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.escalation_api import EscalationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEscalationApi(unittest.TestCase):
    """EscalationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.escalation_api.EscalationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_escalation(self):
        """Test case for create_escalation

        Create Escalation  # noqa: E501
        """
        pass

    def test_delete_escalation(self):
        """Test case for delete_escalation

        Delete Escalation  # noqa: E501
        """
        pass

    def test_get_escalation(self):
        """Test case for get_escalation

        Get Escalation  # noqa: E501
        """
        pass

    def test_list_escalations(self):
        """Test case for list_escalations

        List Escalations  # noqa: E501
        """
        pass

    def test_update_escalation(self):
        """Test case for update_escalation

        Update Escalation (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
