# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.policy_api import PolicyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.policy_api.PolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_policy_order(self):
        """Test case for change_policy_order

        Change Policy Order  # noqa: E501
        """
        pass

    def test_create_policy(self):
        """Test case for create_policy

        Create Policy  # noqa: E501
        """
        pass

    def test_delete_policy(self):
        """Test case for delete_policy

        Delete Policy  # noqa: E501
        """
        pass

    def test_disable_policy(self):
        """Test case for disable_policy

        Disable Policy  # noqa: E501
        """
        pass

    def test_enable_policy(self):
        """Test case for enable_policy

        Enable Policy  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        Get Policy  # noqa: E501
        """
        pass

    def test_list_alert_policies(self):
        """Test case for list_alert_policies

        List Alert Policies  # noqa: E501
        """
        pass

    def test_list_notification_policies(self):
        """Test case for list_notification_policies

        List Notification Policies  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Update Policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
