# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.who_is_on_call_api import WhoIsOnCallApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWhoIsOnCallApi(unittest.TestCase):
    """WhoIsOnCallApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.who_is_on_call_api.WhoIsOnCallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_on_call_user(self):
        """Test case for export_on_call_user

        Export On-Call User  # noqa: E501
        """
        pass

    def test_get_next_on_calls(self):
        """Test case for get_next_on_calls

        Get Next On Calls  # noqa: E501
        """
        pass

    def test_get_on_calls(self):
        """Test case for get_on_calls

        Get On Calls  # noqa: E501
        """
        pass

    def test_list_on_calls(self):
        """Test case for list_on_calls

        List On Calls  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
