# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.schedule_recipient import ScheduleRecipient  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduleRecipient(unittest.TestCase):
    """ScheduleRecipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleRecipient(self):
        """Test ScheduleRecipient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.schedule_recipient.ScheduleRecipient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
