# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.google_stack_driver_integration import GoogleStackDriverIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestGoogleStackDriverIntegration(unittest.TestCase):
    """GoogleStackDriverIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoogleStackDriverIntegration(self):
        """Test GoogleStackDriverIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.google_stack_driver_integration.GoogleStackDriverIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
