# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.notification_repeat import NotificationRepeat  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationRepeat(unittest.TestCase):
    """NotificationRepeat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationRepeat(self):
        """Test NotificationRepeat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.notification_repeat.NotificationRepeat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
