# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.heartbeat_api import HeartbeatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHeartbeatApi(unittest.TestCase):
    """HeartbeatApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.heartbeat_api.HeartbeatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_heartbeat(self):
        """Test case for create_heartbeat

        Create Heartbeat  # noqa: E501
        """
        pass

    def test_delete_heartbeat(self):
        """Test case for delete_heartbeat

        Delete Heartbeat  # noqa: E501
        """
        pass

    def test_disable_heartbeat(self):
        """Test case for disable_heartbeat

        Disable Heartbeat  # noqa: E501
        """
        pass

    def test_enable_heartbeat(self):
        """Test case for enable_heartbeat

        Enable Heartbeat  # noqa: E501
        """
        pass

    def test_get_heartbeat(self):
        """Test case for get_heartbeat

        Get Heartbeat  # noqa: E501
        """
        pass

    def test_list_heart_beats(self):
        """Test case for list_heart_beats

        List Heartbeats  # noqa: E501
        """
        pass

    def test_ping(self):
        """Test case for ping

        Ping Heartbeat  # noqa: E501
        """
        pass

    def test_update_heartbeat(self):
        """Test case for update_heartbeat

        Update Heartbeat (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
