# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_now_integration import ServiceNowIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceNowIntegration(unittest.TestCase):
    """ServiceNowIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceNowIntegration(self):
        """Test ServiceNowIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_now_integration.ServiceNowIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
