# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ring_central_glip_integration import RingCentralGlipIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestRingCentralGlipIntegration(unittest.TestCase):
    """RingCentralGlipIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRingCentralGlipIntegration(self):
        """Test RingCentralGlipIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ring_central_glip_integration.RingCentralGlipIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
