# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_rule_step_api import NotificationRuleStepApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationRuleStepApi(unittest.TestCase):
    """NotificationRuleStepApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notification_rule_step_api.NotificationRuleStepApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_notification_rule_step(self):
        """Test case for create_notification_rule_step

        Create Notification Rule Step  # noqa: E501
        """
        pass

    def test_delete_notification_rule_step(self):
        """Test case for delete_notification_rule_step

        Delete Notification Rule Step  # noqa: E501
        """
        pass

    def test_disable_notification_rule_step(self):
        """Test case for disable_notification_rule_step

        Disable Notification Rule Step  # noqa: E501
        """
        pass

    def test_enable_notification_rule_step(self):
        """Test case for enable_notification_rule_step

        Enable Notification Rule Step  # noqa: E501
        """
        pass

    def test_get_notification_rule_step(self):
        """Test case for get_notification_rule_step

        Get Notification Rule Step  # noqa: E501
        """
        pass

    def test_list_notification_rule_steps(self):
        """Test case for list_notification_rule_steps

        List Notification Rule Steps  # noqa: E501
        """
        pass

    def test_update_notification_rule_step(self):
        """Test case for update_notification_rule_step

        Update Notification Rule Step (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
