# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.slack_integration import SlackIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestSlackIntegration(unittest.TestCase):
    """SlackIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSlackIntegration(self):
        """Test SlackIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.slack_integration.SlackIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
