# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.prtg_integration import PrtgIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestPrtgIntegration(unittest.TestCase):
    """PrtgIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrtgIntegration(self):
        """Test PrtgIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.prtg_integration.PrtgIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
