# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_alerts_response import ListAlertsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListAlertsResponse(unittest.TestCase):
    """ListAlertsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAlertsResponse(self):
        """Test ListAlertsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_alerts_response.ListAlertsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
