# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.kapacitor_integration import KapacitorIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestKapacitorIntegration(unittest.TestCase):
    """KapacitorIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKapacitorIntegration(self):
        """Test KapacitorIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.kapacitor_integration.KapacitorIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
