# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.signal_fxv2_integration import SignalFXV2Integration  # noqa: E501
from swagger_client.rest import ApiException


class TestSignalFXV2Integration(unittest.TestCase):
    """SignalFXV2Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalFXV2Integration(self):
        """Test SignalFXV2Integration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.signal_fxv2_integration.SignalFXV2Integration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
