# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.team_api import TeamApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.team_api.TeamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_team(self):
        """Test case for create_team

        Create Team  # noqa: E501
        """
        pass

    def test_delete_team(self):
        """Test case for delete_team

        Delete Team  # noqa: E501
        """
        pass

    def test_get_team(self):
        """Test case for get_team

        Get Team  # noqa: E501
        """
        pass

    def test_list_team_logs(self):
        """Test case for list_team_logs

        List Team Logs  # noqa: E501
        """
        pass

    def test_list_teams(self):
        """Test case for list_teams

        List Teams  # noqa: E501
        """
        pass

    def test_update_team(self):
        """Test case for update_team

        Update Team (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
