# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.loggly_integration import LogglyIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestLogglyIntegration(unittest.TestCase):
    """LogglyIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogglyIntegration(self):
        """Test LogglyIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.loggly_integration.LogglyIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
