# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.incident_request_status import IncidentRequestStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestIncidentRequestStatus(unittest.TestCase):
    """IncidentRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncidentRequestStatus(self):
        """Test IncidentRequestStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.incident_request_status.IncidentRequestStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
