# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.x_pack_alerting_integration import XPackAlertingIntegration  # noqa: E501
from swagger_client.rest import ApiException


class TestXPackAlertingIntegration(unittest.TestCase):
    """XPackAlertingIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXPackAlertingIntegration(self):
        """Test XPackAlertingIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.x_pack_alerting_integration.XPackAlertingIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
