# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.amazon_sns_callback import AmazonSnsCallback  # noqa: E501
from swagger_client.rest import ApiException


class TestAmazonSnsCallback(unittest.TestCase):
    """AmazonSnsCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmazonSnsCallback(self):
        """Test AmazonSnsCallback"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.amazon_sns_callback.AmazonSnsCallback()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
