# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.team_member_api import TeamMemberApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamMemberApi(unittest.TestCase):
    """TeamMemberApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.team_member_api.TeamMemberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_team_member(self):
        """Test case for add_team_member

        Add Team Member  # noqa: E501
        """
        pass

    def test_delete_team_member(self):
        """Test case for delete_team_member

        Delete Team Member  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
