# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_alert_attachments_response import ListAlertAttachmentsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListAlertAttachmentsResponse(unittest.TestCase):
    """ListAlertAttachmentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAlertAttachmentsResponse(self):
        """Test ListAlertAttachmentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_alert_attachments_response.ListAlertAttachmentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
