# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.site24x7_integration import Site24x7Integration  # noqa: E501
from swagger_client.rest import ApiException


class TestSite24x7Integration(unittest.TestCase):
    """Site24x7Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSite24x7Integration(self):
        """Test Site24x7Integration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.site24x7_integration.Site24x7Integration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
