# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.team_role_api import TeamRoleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamRoleApi(unittest.TestCase):
    """TeamRoleApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.team_role_api.TeamRoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_team_role(self):
        """Test case for create_team_role

        Create Team Role  # noqa: E501
        """
        pass

    def test_delete_team_role(self):
        """Test case for delete_team_role

        Delete Team Role  # noqa: E501
        """
        pass

    def test_get_team_role(self):
        """Test case for get_team_role

        Get Team Role  # noqa: E501
        """
        pass

    def test_list_team_roles(self):
        """Test case for list_team_roles

        List Team Roles  # noqa: E501
        """
        pass

    def test_update_team_role(self):
        """Test case for update_team_role

        Update Team Role (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
