# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_integration_response import CreateIntegrationResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateIntegrationResponse(unittest.TestCase):
    """CreateIntegrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateIntegrationResponse(self):
        """Test CreateIntegrationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_integration_response.CreateIntegrationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
