# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.integration_action_api import IntegrationActionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntegrationActionApi(unittest.TestCase):
    """IntegrationActionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.integration_action_api.IntegrationActionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_integration_action(self):
        """Test case for create_integration_action

        Create Integration Action  # noqa: E501
        """
        pass

    def test_list_integration_actions(self):
        """Test case for list_integration_actions

        List Integration Actions  # noqa: E501
        """
        pass

    def test_update_integration_actions(self):
        """Test case for update_integration_actions

        Update Integration Actions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
