# coding: utf-8

# flake8: noqa
"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
