# coding: utf-8

"""
    Opsgenie REST API

    Opsgenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HPServiceManagerCallback(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_ket': 'str',
        'base_domain': 'str'
    }

    attribute_map = {
        'api_ket': 'apiKet',
        'base_domain': 'baseDomain'
    }

    def __init__(self, api_ket=None, base_domain=None):  # noqa: E501
        """HPServiceManagerCallback - a model defined in Swagger"""  # noqa: E501

        self._api_ket = None
        self._base_domain = None
        self.discriminator = None

        if api_ket is not None:
            self.api_ket = api_ket
        if base_domain is not None:
            self.base_domain = base_domain

    @property
    def api_ket(self):
        """Gets the api_ket of this HPServiceManagerCallback.  # noqa: E501


        :return: The api_ket of this HPServiceManagerCallback.  # noqa: E501
        :rtype: str
        """
        return self._api_ket

    @api_ket.setter
    def api_ket(self, api_ket):
        """Sets the api_ket of this HPServiceManagerCallback.


        :param api_ket: The api_ket of this HPServiceManagerCallback.  # noqa: E501
        :type: str
        """

        self._api_ket = api_ket

    @property
    def base_domain(self):
        """Gets the base_domain of this HPServiceManagerCallback.  # noqa: E501


        :return: The base_domain of this HPServiceManagerCallback.  # noqa: E501
        :rtype: str
        """
        return self._base_domain

    @base_domain.setter
    def base_domain(self, base_domain):
        """Sets the base_domain of this HPServiceManagerCallback.


        :param base_domain: The base_domain of this HPServiceManagerCallback.  # noqa: E501
        :type: str
        """

        self._base_domain = base_domain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HPServiceManagerCallback, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HPServiceManagerCallback):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
